#!/usr/bin/env python
import click
import rospy

from rosparam_expose.srv import Set, Get

SRV_NS = '/rosparam_expose'


@click.group()
def client():
    pass


@click.command('set')
@click.argument('name')
@click.argument('value')
@click.option('--timeout', default=5, help='number of seconds to wait for service')
def set_param(name, value, timeout):
    srv = SRV_NS + '/set'
    rospy.wait_for_service(srv, timeout=timeout)
    try:
        srv_proxy = rospy.ServiceProxy(srv, Set)
        response = srv_proxy(name, value)
        click.echo(response)
    except rospy.ServiceException, e:
        click.echo('Service all failed: {}'.format(e), err=True)


@click.command('get')
@click.argument('name')
@click.option('--timeout', default=5, help='number of seconds to wait for service')
def get_param(name, timeout):
    srv = SRV_NS + '/get'
    rospy.wait_for_service(srv, timeout=timeout)
    try:
        srv_proxy = rospy.ServiceProxy(srv, Get)
        response = srv_proxy(name)
        click.echo(response.value)
    except rospy.ServiceException, e:
        click.echo('Service all failed: {}'.format(e), err=True)


if __name__ == '__main__':
    client.add_command(set_param)
    client.add_command(get_param)
    client()
