#!/bin/bash

if [ -z "$1" ]; then
  echo Need xacro filepath
  exit 1
fi

if [ -z "$2" ]; then
  echo Need parameter name
  exit 1
fi

tmpfile=$(mktemp)
rosrun xacro xacro "$1" | tee $tmpfile >/dev/null
rosrun rosparam_expose client set "$2" --textfile $tmpfile
