#!/usr/bin/env python
import rospy
import yaml

from rosparam_expose.srv import Set, Get

NODE_NAME = 'rosparam_expose'
SRV_NS = '/rosparam_expose'


def set_handler(req):
    rospy.loginfo('set_handler request: name:%s value:%s', req.name, req.value)
    rospy.set_param(req.name, yaml.safe_load(req.value))
    return []


def get_handler(req):
    rospy.loginfo('get_handler request: name:%s', req.name)
    value = yaml.safe_dump(rospy.get_param(req.name))
    if value.endswith('\n...\n'):
        value = value[:-5]
    rospy.loginfo('get_handler response: value:%s', value)
    return [value]


if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    rospy.Service(SRV_NS + '/set', Set, set_handler)
    rospy.Service(SRV_NS + '/get', Get, get_handler)
    rospy.spin()
